//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Test.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary
        ///    xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///    xmlns:controls=&quot;clr-namespace:System.Windows.Controls.Markdown&quot;&gt;
        ///
        ///    &lt;SolidColorBrush x:Key=&quot;MarkdownBorderBrush&quot; Color=&quot;#ffffff&quot; /&gt;
        ///    &lt;SolidColorBrush x:Key=&quot;MarkdownSubBackgroundBrush&quot; Color=&quot;#20ffffff&quot; /&gt;
        ///    &lt;SolidColorBrush x:Key=&quot;MarkdownBackgroundBrush&quot; Color=&quot;Transparent&quot; /&gt;
        ///
        ///    &lt;Style TargetType=&quot;controls:MarkdownTextBlock&quot;&gt;
        ///        &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResourceDictionary1 {
            get {
                return ResourceManager.GetString("ResourceDictionary1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;UserControl
        ///    x:Class=&quot;System.Windows.Test.UserControl1&quot;
        ///    xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///    xmlns:local=&quot;using:System.Windows.Test&quot;
        ///    xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot;
        ///    xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;
        ///    mc:Ignorable=&quot;d&quot;
        ///    d:DesignHeight=&quot;300&quot;
        ///    d:DesignWidth=&quot;400&quot;&gt;
        ///
        ///    &lt;Viewbox Width=&quot;64&quot; Height=&quot;64&quot; Margin=&quot;16&quot; Horizont [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserControl1 {
            get {
                return ResourceManager.GetString("UserControl1", resourceCulture);
            }
        }
    }
}
